version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: supreme-card-checker-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/bot_database.db
